name: .NET Build and Package

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-pack:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Pack project
      run: dotnet pack --configuration Release --output ./artifacts

    - name: Debug artifacts directory
      run: ls -la ./artifacts

    - name: Upload package artifact
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-package
        path: ./artifacts
