name: .NET Build, Package, Release, and Publish

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-release-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0'

    - name: Restore dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build ./NumeriCall/ --configuration Release /p:DebugType=None /p:DebugSymbols=false

    - name: Pack project
      run: dotnet pack ./NumeriCall/ --configuration Release --output ./artifacts

    - name: Check Artifact
      run: ls -la ./artifacts

    - name: Create GitHub Release
      run: gh release create "$GITHUB_REF_NAME" --notes "Automated release for $GITHUB_REF_NAME"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload to release using GitHub CLI
      run: gh release upload "$GITHUB_REF_NAME" ./artifacts/*.nupkg
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Publish to GitHub Packages
    #   run: dotnet nuget push ./artifacts/*.nupkg --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
